# smtp.yml


# SMTP Configuration
# For more information: http://guides.rails.info/action_mailer_basics.html

development:
  enable_starttls_auto: true
  address: smtp.gmail.com
  port: 587
  domain: example.com
  authentication: :login
  user_name: example@example.com
  password: password

production:
  enable_starttls_auto: true
  address: smtp.gmail.com
  port: 587
  domain: example.com
  authentication: :login
  user_name: example@example.com
  password: password

test:

